spring:
  datasource:
#    password: password
#    url: jdbc:mysql://localhost:3306/test_system
#    username: root
      password: ${DB_PASSWORD}
      url: jdbc:mysql://${DB_HOST}/${DB_NAME}
      username: ${DB_USERNAME}
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

server:
  error:
    path: /error
    whitelabel:
      enabled: false

upload:
  path: uploads