spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/test_system
    username: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

server:
  error:
    path: /error
    whitelabel:
      enabled: false

upload:
  path: uploads