name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test_system
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - uses: actions/checkout@v3.3.0
    
    - uses: actions/setup-java@v3.9.0
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
      env:
          DB_HOST: mysql:3306
          DB_USERNAME: root
          DB_PASSWORD: ""
          DB_DATABASE: test_system
    - name: Build with Maven
      run: mvn -B package --file pom.xml
