name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-system-course-work"
          heroku_email: "amerscan8@gmail.com"
          branch: master
        env:
          HD_LANG: C.UTF-8
          HD_LC_ALL: C.UTF-8
